# Generated by Django 5.2.7 on 2026-06-04 23:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='libros.ejemplar')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_devolucion__isnull', True)), fields=('ejemplar',), name='prestamo_activo_unico_por_ejemplar')],
            },
        ),
    ]
