# Generated by Django 5.2.7 on 2026-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='ejemplar',
            unique_together={('libro', 'codigo')},
        ),
    ]
